<?php // in module/Application/view/partial/breadcrumb.html:?>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <?php
    //irerate through the pages
    foreach($this->pages as $key => $page): ?>
        <?php 
        //if this isn'tthe last page, add a link and separator:
        if($key < count($this->pages) - 1):
          ?>
          <li class="breadcrumb-item">
            <a href="<?= $page->getHref() ?>">
              <?= $page->getLabel() ?>
            </a>
          </li>
        <?php 
        // otherwise, output the name only:
          else:
              ?>
              <li class="breadcrumb-item active" aria-current="page">
                <?= $page->getLabel() ?>
              </li>
        <?php endif; ?>
    <?php endforeach; ?>
  </ol>
</nav>
