<?php
$title = 'Add new Command';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$command = $form->get('command');
$command->setAttribute('class', 'form-control');
$command->setAttribute('placeholder', 'Command');

// This provides a default CSS class and placeholder text for the artist element:
$explanation = $form->get('explanation');
$explanation->setAttribute('class', 'form-control');
$explanation->setAttribute('placeholder', 'Explanation');

$type = $form->get('type');
$type->setAttribute('class', 'form-control');
$type->setAttribute('placeholder', 'Type');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($command) ?>
    <?= $this->formElement($command) ?>
    <?= $this->formElementErrors()->render($command, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($explanation) ?>
    <?= $this->formElement($explanation) ?>
    <?= $this->formElementErrors()->render($explanation, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($type) ?>
    <?= $this->formElement($type) ?>
    <?= $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();