<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete album';
$url   = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p> "<?= $this->escapeHtml($album->command) ?>" </p>
<p> "<?= $this->escapeHtml($album->explanation)?>" </p>
<p> "<?= $this->escapeHtml($album->type)?>"</p>
<p> これらを削除しても良いですか？</p>


<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>