<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$command = $form->get('command');
$command->setAttribute('class', 'form-control');
$command->setAttribute('placeholder', 'Command');

$explanation = $form->get('explanation');
$explanation->setAttribute('class', 'form-control');
$explanation->setAttribute('placeholder', 'Explanation');

$type = $form->get('type');
$type->setAttribute('class', 'form-control');
$type->setAttribute('placeholser', 'Type');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($command) ?>
    <?= $this->formElement($command) ?>
    <?= $this->formElementErrors()->render($command, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($explanation) ?>
    <?= $this->formElement($explanation) ?>
    <?= $this->formElementErrors()->render($explanation, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($type) ?>
    <?= $this->formElement($type) ?>
    <?= $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>